### ISSUE TITLE
[JOSS review] Documentation of dat file / database format

### ISSUE THREAD

**Issue by mefuller** [ORNL/Equilipy#2]
Please add clear(er) identification of the database file format and appropriate links in the web documentation and paper, including making clear the current limitations on components in the web documentation.

**Comment by SunyongKwon** [comment]
Hi @mefuller,

First of all thank you so much for your suggestion. I completely agree with you. I added the description regarding the database format and the current version of database in the web documentation under `Database`.

FYI, we are not planning on providing a complete set of database in `equilipy`, since developing database by itself requires tremendous amount of work. Database development will be launched as a separate project in the future.
